//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballPlayerStatWebApp.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KovalevDO_IDZEntities : DbContext
    {
        public KovalevDO_IDZEntities()
            : base("name=KovalevDO_IDZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<CoachCareer> CoachCareers { get; set; }
        public virtual DbSet<Game_Player> Game_Player { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerCareer> PlayerCareers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Trophy> Trophies { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
