//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballPlayerStatWebApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCareer
    {
        public int CareerId { get; set; }
        public int Number { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Position { get; set; }
        public int PlayerId { get; set; }
        public int ClubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Player Player { get; set; }
    }
}
